services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=giftcard'
      - 'POSTGRES_PASSWORD=Giftcard*123#'
      - 'POSTGRES_USER=giftcard'
    ports:
      - '5432'
